### ISSUE TITLE
PortalDestination is required to be created at the same time or after PortalSource

### ISSUE THREAD

**Issue by SaphuA** [pivotal-cf/pivotal-ui#469]
I'm having some issues with portals in a **NON** single page application using webpack.

At the root of my layout I have defined a PortalDestination:

    <PortalDestination name="global" />

Then I have a component that contains a PortalSource that gets displayed conditionally.

    {this.state.showDimmer && (
        <PortalSource name="global">
            <Dimmer text="Hello world" />
        </PortalSource>
    )}

This does not work...

Strange enough, it does work when, I create another empty PortalDestination at the same time or after the PortalSource is created. Like this:

    {this.state.showDimmer && (
        <span>
            <PortalSource name="global">
                <Dimmer text="Hello world" />
            </PortalSource>
            <PortalDestination />
        </span>
    )}

The second PortalDestination can be created anywhere, as long as it's created at the same time or after PortalSource. Also the second PortalDestination is not used. The PortalDestination with name 'global' is actually used.

I am pretty sure this is because PortalSource is dependent on an event that gets emitted by PortalDestination.

Also, a small sidenote: it seems that Webpack (or typescript) is creating local variables of destinationPortals and the emitter. I am assuming these need to be global?

**Comment by SaphuA** [comment]
It seems that PortalSource is dependent on the emitter the be called after it is created.

Also, I'm using webpack which is making local variables of destinationPortals and the emitter. I'm assuming these should be global?

**Comment by charleshansen** [comment]
Portals definitely rely on only having one class definition. This way there is only one event emitter that they share. I assume if you try to use portals across two different apps, they will not work. The event emitter and destination portals don't need to be global as long as there is only one definition of the Portal component on the page. This should work just fine with Webpack for a single page app.

It is also true that the Portal Source does need to be rendered at the same time or before the Portal Destination. We never really ran into a use case where this was a problem, though it sounds like you are.

The other issue here is that I am not aware of any team actually using Portals in production, so they probably have some rough edges. We invented them to solve a particular problem with Modals, but then we found a more idiomatic React method for Modals and then never used it again. We kept it around just in case and almost used them a couple times, but never actually did. In general, Portals are a pretty heavy tool and there is usually a simpler way to do anything you would use a Portal for. 

Can you give me more details on what you need the Portals to actually do? I'm not sure if we can fix it or not. I may also be able to point you to a different component that has more users.

**Comment by SaphuA** [comment]
Thanks for the in-depth response!

I am working on a web app that uses standalone React components for bits of functionality. A few of these components need to display a modal. Some of these components are displayed in a fixed div so it's very cumbersome to display a modal in them. After some googling I came across Pivotal's Portals which seems perfect for the job. Maintaining React's functionality in these modals is very important for us.

Besides the fact that I need to create a destination after a source, Portals seem to be working great.

**Comment by SaphuA** [comment]
@charleshansen did you have a chance to look into this or can you suggest a better alternative?

**Comment by charleshansen** [comment]
Hey @SaphuA sorry about the delay. Do your components need to each display modals in different places? If they all display modals in the normal place in the page, you can use the Pivotal UI modal component itself and it should work. I don't think I'm going to have time to make modals work across different React apps myself. I do think if you make the emitter and the destination portals globals it may work for you. It would just have other weird effects I wouldn't want to publish in PUI (who knows what would happen with server side rendering for example).

**Comment by steodor** [comment]
Hi. I have a page title as a standalone component with a `PortalDestination` and i tried to use `PortalSource` in individual components to render the page title depending on which page is currently displayed. 

Of course, this does not work since `PortalSource` gets rendered after `PortalDestination` and doesn't do anything, while the `PortalDestination` is in the header of the page since the first rendering.

I fixed it by introducing a call to `this.setDestination()` inside the `render()` function of `PortalSource`, so that the destination will reflect changes when a source is rendered. So in the `PortalSource` component:

```
    render() {
        this.setDestination(); // <- i added this line
        return null;
    }
```

Now, every time my page changes, a `PortalSource` is rendered and this reflects in my `PortalDestination`.

If the destination is already set (i.e. the `PortalSource` changes in time after the first time it was rendered) then i have no idea if changes will reflect, but fortunately my use case doesn't need it.

@SaphuA i hope this helps, and @charleshansen if more people try to use it this way, then maybe it would make sense to redesign this component a bit to enable more use-cases (my solution is only a quick hack, of course). Cheers 🍺

**Comment by charleshansen** [comment]
@steodor I may not fully understand your use case, but I think if I wanted to do the same thing, I would use basic flux patterns for this. I would save some kind of meta-data about the page title in my top level store and any component who wants to update the page title can dispatch some action to change the page title data in the store, which should change how the page title renders. This should be easier to test and shouldn't require any hacks.

**Comment by steodor** [comment]
@charleshansen I ended up doing just that actually, via Redux. However, i still think this component could be more versatile, i mean, the fact that it depends on mounting order makes it brittle. More so when [the docs](http://styleguide.pivotal.io/react_components_portals.html) state: "If a `PortalDestination` is put at the bottom of `<body>`, a `PortalSource` **can then** be used anywhere [...]" (my highlight) when in fact it can't, because `PortalSource` would then be mounted **after** `PortalDestination` and wouldn't work. Hence the confusion.

Also, the fact that it fails silently, without generating at least a console message, leaves devs clueless. Since this was a basic scenario, it hints that there may also be other ones which are not being handled at all. This in turn raises questions about the overall quality of the entire framework. I only dug into this component's source code because i expected it to be small and simple, which it is. But as much as i'd like to help, i just don't have the time to debug more complicated components. I need to get things done faster than doing them myself, and i think this is the whole point of any framework. It's a pity when i can't.

Now i guess you could either update the docs and make this limitation clear, or make it work both ways. Personally i'd choose the latter, but it's your call. Good luck! 👍

**Comment by charleshansen** [comment]
Good point about the docs, I can at least fix those up. 

I'm still torn on the Portal component. I still can't name a situation when anyone should ever actually use it, even if I fix the mounting order issue. I'd rather not provide a component that people should not use.

**Comment by charleshansen** [comment]
Eh, I fixed it anyway 90820be73f796a264d4f4675918a96af16cf18d8. I was curious how the timing actually worked. For what it is worth, it did work fine if the `PortalDestination` is at the bottom of the body. The only issue is when the `PortalSource` is not rendered anywhere at first, and then rendered later.

**Comment by SaphuA** [comment]
Thanks a lot @steodor and @charleshansen
